// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 32-bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Wed Dec 12 15:47:43 2018

spi_core spi_core_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset_n(reset_n_sig) ,	// input  reset_n_sig
	.miso(miso_sig) ,	// input  miso_sig
	.go_transfer(go_transfer_sig) ,	// input  go_transfer_sig
	.data_write_from_avalon(data_write_from_avalon_sig) ,	// input [31:0] data_write_from_avalon_sig
	.sclk(sclk_sig) ,	// output  sclk_sig
	.ss_n(ss_n_sig) ,	// output  ss_n_sig
	.mosi(mosi_sig) ,	// output  mosi_sig
	.data_read_to_avalon(data_read_to_avalon_sig) ,	// output [31:0] data_read_to_avalon_sig
	.data_pack_ready(data_pack_ready_sig) 	// output  data_pack_ready_sig
);

